server:
  port: 8080
  servlet:
    context-path: /WineStore

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/WineStore"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: "TaoThachThucChungMayDoanDuocJWTSercetKeyCuaTaoDoDoanDuocLamConChohahaha"
    expiration-ms: 1800000
    remember-expiration-ms: 86400000